project_id = "cifbetjefyfocafanlhv"

[functions.live-chat]
verify_jwt = false

[functions.webrtc-signaling]
verify_jwt = false

[functions.create-product-request]
verify_jwt = false

[functions.analyze-itakecare-catalog]
verify_jwt = true