project_id = "cifbetjefyfocafanlhv"

[functions.render-offer-pdf]
verify_jwt = true

[functions.render-offer-pdf-v2]
verify_jwt = true

[functions.company-search]
verify_jwt = false

[functions.catalog-api]
verify_jwt = false

[functions.redirect-upload]
verify_jwt = false

[functions.live-chat]
verify_jwt = false

[functions.webrtc-signaling]
verify_jwt = false

[functions.create-product-request]
verify_jwt = false

[functions.analyze-itakecare-catalog]
verify_jwt = true

[functions.generate-auth-link]
verify_jwt = false

[functions.create-account-custom]
verify_jwt = false

[functions.custom-login]
verify_jwt = false

[functions.custom-password-reset] 
verify_jwt = false

[functions.update-password-custom]
verify_jwt = false

[functions.send-account-deleted-email]
verify_jwt = false

[functions.get-company-logo]
verify_jwt = false

[functions.get-ambassador-company]
verify_jwt = false

[functions.verify-custom-token]
verify_jwt = false

[functions.send-document-rejection]
verify_jwt = true

[functions.send-document-request]
verify_jwt = false

[functions.get-secret]
verify_jwt = true

[functions.france-company-lookup]
verify_jwt = false

[functions.belgium-company-lookup]
verify_jwt = false

[functions.belgium-company-lookup-enhanced]
verify_jwt = false

[functions.vies-verify]
verify_jwt = false

[functions.luxembourg-company-lookup]
verify_jwt = false

[functions.notify-admins-document-upload]
verify_jwt = true

[functions.send-leasing-acceptance-email]
verify_jwt = false

[functions.send-leasing-rejection-email]
verify_jwt = false

[functions.import-contracts-2025]
verify_jwt = true

[functions.import-contracts-multi-years]
verify_jwt = true

[functions.migrate-product-images]
verify_jwt = true

[functions.generate-offer-images]
verify_jwt = true

[functions.send-offer-email]
verify_jwt = true

[functions.import-meta-leads]
verify_jwt = false

[functions.billit-import-invoices]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false